version: "3.9"

services:
  postgres:
    image: postgres:13
    container_name: chatbot_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  rasa:
    image: rasa/rasa:3.6.20-full
    container_name: rasa_full
    working_dir: /app
    volumes:
      - ./src/rasa:/app
    command: [ "run", "--enable-api", "--cors", "*", "--port", "5005", "--debug" ]
    ports:
      - "${RASA_PORT}:5005"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POSTGRES_DB=${POSTGRES_DB}
      - SQLALCHEMY_WARN_20=0
      - SQLALCHEMY_SILENCE_UBER_WARNING=1

  rasa-actions:
    build:
      context: .
      dockerfile: Dockerfile.actions
    ports:
      - "${PORT_RASA_ACTIONS}:5055"
    volumes:
      - ./src/actions:/app/actions
      - ./src/nlp:/app/nlp
    entrypoint: [ "python", "-m", "rasa_sdk" ]
    command: [ "--actions", "actions", "--debug" ]
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: chatbot_fastapi
    ports:
      - "${API_PORT}:8000"
    volumes:
      - ./src/api:/app
    depends_on:
      - rasa
      - postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - RASA_API_URL=http://rasa:5005/webhooks/rest/webhook
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/${POSTGRES_DB}
      - MAX_RETRIES=10
      - RETRY_DELAY=5
    restart: unless-stopped

volumes:
  postgres_data:
