language: es

pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: CountVectorsFeaturizer
- name: DIETClassifier
  epochs: 100
  constrain_similarities: true
- name: EntitySynonymMapper
- name: FallbackClassifier
  threshold: 0.5              # cuando NLU no entiende
  ambiguity_threshold: 0.1

policies:
  # Memoización para historias exactas
- name: MemoizationPolicy

  # Reglas
- name: RulePolicy
  core_fallback_threshold: 0.3        # cuando Core no sabe qué acción ejecutar
  core_fallback_action_name: action_default_fallback
  enable_fallback_prediction: true

  # Política de aprendizaje (DIET / TED)
- name: TEDPolicy
  max_history: 5
  epochs: 100
  constrain_similarities: true
assistant_id: 20251203-191340-patient-officer
